---
  title: "NFL Score Prediction Model: Feature Engineering"
author: "Wade Fuller"
date: "11/28/2025"
output:
  pdf_document: default
html_document: default
editor_options: 
  markdown: 
  wrap: 72
---
  
```{r setup, include=FALSE}
# ==================================
# NFL PREDICTOR: FEATURE ENGINEERING
# ==================================
library(knitr)
knitr::opts_chunk$set(cache = TRUE, echo = TRUE,
                      message = FALSE, dpi = 180,
                      fig.width = 8, fig.height = 5)
knitr::opts_knit$set(root.dir = "~/Projects/R/")
library(tidyverse)
library(nflfastR)
library(ggthemes)
library(zoo)
library(doParallel)
theme_set(theme_minimal(base_size = 10))
```

# Introduction

Create a feature set for each NFL game from 2000-2021 with various
trending and rolling statistics that can be used in modeling game
outcomes.

```{r init}
# CONSTANTS

SEASONS <- 2000:2021 

TEAM_REPLACEMENTS <- c(
  "JAC" = "JAX",
  "SD" = "LAC",
  "OAK" = "LV",
  "STL" = "LA"
)

COMMON_VARS <- c(
  "game_id", "gameday", "season", "week", "weekday", 
  "gametime", "spread_line", "total_line", 
  "home_spread_odds", "away_spread_odds", "home_moneyline","away_moneyline","div_game","result"
)

METRICS <- c(
  'win','result','points_for','spread_cover',
  'spread_adjusted_result','impl_win_prob','game_info_gain',
  'win_prob_captured'
)

DIFFERENTIAL_COLS <- c(
  "win_season_avg","result_season_avg", 
  "points_for_season_avg","spread_cover_season_avg",
  "spread_adjusted_result_season_avg",
  "impl_win_prob_season_avg","game_info_gain_season_avg",
  "win_prob_captured_season_avg",
  "win_4gm_trend","result_4gm_trend",
  "points_for_4gm_trend","spread_cover_4gm_trend",
  "spread_adjusted_result_4gm_trend",
  "impl_win_prob_4gm_trend",
  "game_info_gain_4gm_trend", "win_prob_captured_4gm_trend",
  "off_epa_r4","off_epa_r16",
  "off_pass_epa_r4","off_pass_epa_r16",
  "off_rush_epa_r4","off_rush_epa_r16",
  "success_rate_r4","success_rate_r16",
  "qb_epa_r4","qb_epa_r16",
  "pythag_win_pct","pythag_wins"
)

FEATURES <- c(
  # GAME FEATURES W/ TRENDS
  "team","opposing_team","points_for","points_against","total_points_scored","pct_points_scored","team_rest","opponent_rest",
  "impl_prob_home","impl_prob_away","home","win","spread_adjusted_result","spread_cover","impl_win_prob","rest_diff","game_info_gain",
  "win_prob_captured","win_season_avg","result_season_avg","points_for_season_avg","spread_cover_season_avg","spread_adjusted_result_season_avg",
  "impl_win_prob_season_avg","game_info_gain_season_avg","win_prob_captured_season_avg","win_4gm_trend","result_4gm_trend",
  "points_for_4gm_trend","spread_cover_4gm_trend","spread_adjusted_result_4gm_trend","impl_win_prob_4gm_trend",
  "game_info_gain_4gm_trend", "win_prob_captured_4gm_trend",
  # EPA
  "off_epa","off_pass_epa","off_rush_epa","success_rate","qb_epa","off_epa_r4","off_epa_r12","off_epa_r16",
  "off_pass_epa_r4","off_pass_epa_r12","off_pass_epa_r16","off_rush_epa_r4","off_rush_epa_r12","off_rush_epa_r16",
  "success_rate_r4","success_rate_r12","success_rate_r16","qb_epa_r4","qb_epa_r12","qb_epa_r16"
)

# HELPER FUNCTIONS

load_game_data <- function() {
  games <- readRDS(url("http://www.habitatring.com/games.rds")) %>%
    filter(season >= min(SEASONS)) %>%
    normalize_team_names()
  return(games)
}

normalize_team_names <- function(games) {
  games %>% mutate(across(
    .cols = contains("team") # Select columns with "team" in name
    ,.fns = ~str_replace_all(., TEAM_REPLACEMENTS)  # Apply replacements
  ))
}

calculate_rolling_stats <- function() {
  set_names(paste0(col, "_r", windows))
}

split_home_away <- function(games) {
  home_games <- games %>%
    transmute(
      !!!syms(COMMON_VARS)
      ,team = home_team
      ,opposing_team = away_team
      ,points_for = home_score
      ,points_against = away_score
      ,total_points_scored = total
      ,pct_points_scored = points_for/total_points_scored
      ,team_rest = home_rest
      ,opponent_rest = away_rest
      ,spread_line = spread_line * -1
      ,impl_prob_home = if_else(sign(home_moneyline)== -1,(-1*home_moneyline/((-1*home_moneyline)+100)),(100/(home_moneyline+100)))
      ,impl_prob_away = if_else(sign(away_moneyline)== -1,(-1*away_moneyline/((-1*away_moneyline)+100)),(100/(away_moneyline+100)))
      ,home = 1
    )
  
  away_games <- games %>%
    transmute(
      !!!syms(COMMON_VARS)
      ,team = away_team
      ,opposing_team = home_team
      ,points_for = away_score
      ,points_against = home_score
      ,total_points_scored = total
      ,pct_points_scored = points_for/total_points_scored
      ,team_rest = home_rest
      ,opponent_rest = away_rest
      ,spread_line = spread_line * -1    
      ,impl_prob_home = if_else(sign(home_moneyline)== -1,(-1*home_moneyline/((-1*home_moneyline)+100)),(100/(home_moneyline+100)))
      ,impl_prob_away = if_else(sign(away_moneyline)== -1,(-1*away_moneyline/((-1*away_moneyline)+100)),(100/(away_moneyline+100)))
      ,home=0
    )
  
  bind_rows(home_games, away_games) %>%
    mutate(
      home = as.factor(home)
      ,win = as.integer(result > 0)
      ,spread_adjusted_result = spread_line + result
      ,spread_cover = as.integer(spread_adjusted_result > 0)
      ,impl_win_prob = if_else(home == 1, impl_prob_home, impl_prob_away)
      ,rest_diff = team_rest - opponent_rest
      ,game_info_gain = if_else(win == 1,pmax(1-2*impl_win_prob^3,0, na.rm = TRUE),pmax(1-2*impl_win_prob^3-1,-1, na.rm = TRUE))
      ,win_prob_captured = if_else(win == 1, impl_win_prob,-impl_win_prob)
    )
}

generate_trending_features <- function(game_split) {
  game_split %>%
    arrange(season, team, week) %>%
    group_by(season, team) %>%
    mutate(
      # Season averages (all prior games)
      across(
        all_of(METRICS),
        ~rollapply(., list(-(16:1)), mean, align = 'right', fill = NA, partial = TRUE),
        .names = "{.col}_season_avg"
      ),
      # Trailing 4-week trends
      across(
        all_of(METRICS),
        ~rollapply(., list(-(4:1)), mean, align = 'right', fill = NA, partial = TRUE),
        .names = "{.col}_4gm_trend"
      )
    ) %>%
    ungroup()
}

generate_pythag_features <- function(f_game_split_w_trend) {
  f_game_split_w_trend %>%
    group_by(season, team) %>%
    arrange(season, team, week) %>%
    mutate(
      games_played = row_number() - 1,
      cumsum_pts_for = lag(cumsum(points_for)),
      cumsum_pts_against = lag(cumsum(points_against)),
      pythag_win_pct = (cumsum_pts_for^2.37) / 
        ((cumsum_pts_for^2.37) + (cumsum_pts_against^2.37)),
      pythag_wins = pythag_win_pct * games_played
    ) %>%
    ungroup() %>%
    select(game_id, team, week, season, pythag_win_pct, pythag_wins, games_played)
}

generate_historical_pbp_data <- function() {
  pbp <- nflreadr::load_pbp(seasons = 2000:2021)
  pbp %>%
    filter(
      !is.na(epa), !is.na(ep), !is.na(posteam), !is.na(down),
      play_type %in% c("pass", "run") | penalty == 1,
      qb_kneel != 1
    ) %>%
    normalize_team_names()
}

generate_game_epa <- function(plys) {
  plys %>%
    group_by(game_id, season, week, posteam) %>%
    summarise(
      off_epa = mean(epa),
      off_pass_epa = mean(epa[qb_dropback == 1]),
      off_rush_epa = mean(epa[qb_dropback == 0]),
      success_rate = mean(success[!is.na(success)]),
      qb_epa = mean(qb_epa[!is.na(qb_epa)]),
      .groups = 'drop'
    ) %>%
    rename(team = posteam)
}

generate_rolling_epa_features <- function(game_epa) {
  game_epa %>%
    group_by(team) %>%
    arrange(team, season, week) %>%
    mutate(
      across(
        c(off_epa, off_pass_epa, off_rush_epa, success_rate, qb_epa),
        list(
          r4 = ~rollapply(., list(-(4:1)), mean, align = 'right', fill = NA, partial = TRUE),
          r12 = ~rollapply(., list(-(12:1)), mean, align = 'right', fill = NA, partial = TRUE),
          r16 = ~rollapply(., list(-(16:1)), mean, align = 'right', fill = NA, partial = TRUE)
        )
      )
    ) %>%
    ungroup()
}

combine_features <- function(f_game_split,f_game_split_w_trend,f_game_epa_w_trend,f_pythag) {
  f_game_split %>% 
    left_join(f_game_split_w_trend, by = c("game_id", "season", "week", "team"),suffix = c("", "")) %>%
    left_join(f_game_epa_w_trend, by = c("game_id", "season", "week", "team")) %>%
    left_join(f_pythag, by = c("game_id", "season", "week", "team")) %>%
    select(-ends_with(".x"), -ends_with(".y")) 
}

combine_home_away_differentials <- function(game_w_features) {
home <-  game_w_features %>%
    filter(home == 1) %>%
    rename_with(~ paste0(.x, "_home"),
                all_of(DIFFERENTIAL_COLS)
    )

away <- game_w_features %>%
    filter(home == 0) %>%
    rename_with(~ paste0(.x, "_away"),
                all_of(DIFFERENTIAL_COLS)
    )

  this <- home %>%
    inner_join(
      away, 
      by = "game_id",
      suffix = c("", "")
    ) %>% 
    mutate(
       home_team = team
      ,home_result = result
      ,away_team = opposing_team
      ,home_points = points_for
      ,away_points = points_against
      ,home_pct_points_scored = pct_points_scored
      ,away_pct_points_scored = 1 - pct_points_scored
      ,home_team_rest = team_rest
      ,away_team_rest = opponent_rest
      ,home_win = win
    ) %>%
    mutate(across(
      ends_with("_home"),
      ~. - get(sub("_home$", "_away", cur_column())),
      .names = "{.col}_diff"
    ))
}

```

# Put it all together

```{r Put it all together}
generate_all_features <- function() { 
  message("Loading game data...")
  games <- load_game_data()
  
  message("Splitting home/away...") 
  f_game_split <- split_home_away(games)
  
  message("Generating trending features...") 
  f_game_split_w_trend <- generate_trending_features(f_game_split)
  
  message("Generating pythagorean features...") 
  f_pythag <- generate_pythag_features(f_game_split_w_trend)
  
  message("Loading and processing play-by-play data...") 
  pbp_dta <- generate_historical_pbp_data()
  
  message("Generating EPA features...") 
  f_game_epa <-generate_game_epa(pbp_dta) 
  f_game_epa_w_trend <-generate_rolling_epa_features(f_game_epa)
  
  message("Creating final dataset...") 
  final_df <- combine_features(f_game_split,f_game_split_w_trend,f_game_epa_w_trend,f_pythag)
  
  message("Creating final dataset...") 
  f_df <- combine_home_away_differentials(final_df)
  
  message("Done! Writing to CSV...")
  write_csv(f_df,"~/Projects/R/nfl_predictor/data/game_w_features.csv")
  
  return(final_df) 
}

generate_all_features()

```
